routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['domain' => 'spa.telybazaar.app'], function() {
  Route::get('/', function() {
    return view('admin.spa');
  });
});

Route::get('/', function () {
  // return view('welcome');
  return view('coming-soon');
});

// Route::get('/test', 'API\ProductController@test');
Route::get('test', function() {

    return \App\Category::find(1)->descendantsAndSelf()->pluck('id')->all();
  // return array_unique(\App\Store::all()->pluck('pin')->all());
  // return \App\OrderItem::first()->product;
});
Route::get('/store-based', 'API\ProductController@storeBased');
Route::get('/product-based', 'API\ProductController@productBased');
Route::get('/product-based-single-store', 'API\ProductController@productBasedSingleStore');
Route::get('/calculate-distance', 'API\OrderController@calculateDistance');
Route::get('/reindex-category-names', function() {
  $categories = App\Category::all();
  function findFullName($category) {
    static $names = [];
    array_unshift($names, $category->name);
    if($category->parent_id) {
      return findFullName($category->parent);
    } else {
      $data = implode(' > ', $names);
      $names = [];
      return $data;
    }
  }
  foreach($categories as $category) {
    $category->fullname = findFullName($category);
    echo $category->fullname . '<br>';
    $category->save();
  }
});

Route::get('/login', 'Auth\LoginController@showLoginForm');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/customers', function() {
  return response()->json(\App\Customer::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/address', function() {
  return response()->json(\App\Address::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/products', function() {
  return response()->json(\App\Product::with('stores')->get(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/orders', function() {
  return response()->json(\App\Order::with('storeOrders.orderItems')->get(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/stores', function() {
  return response()->json(\App\Store::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/sample-product-seed', function() {
  foreach(range(0, Request::get('count', 10) - 1) as $i) {
    DB::table('products')->insert([
      'name' => 'foozie',
      'qty' => 20,
      'price' => 20,
      'purchase_price' => 20,
      'category_id' => 1
    ]);
  }
  echo 'seeded ' . (Request::get('count', 10)) . ' items';
});

Route::get('delete-all-products', function() {
  DB::table('products')->delete();
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
  Route::get('/dashboard', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
  Route::get('/dashboard/installs-data', 'DashboardController@installsData');
  Route::get('/dashboard/sales-data', 'DashboardController@salesData');
  Route::get('/notifications', 'AdminController@notifications');

  Route::get('category/tree', 'CategoryController@tree');
  Route::resource('categories', 'CategoryController');

  Route::get('product/{product}/stores', 'ProductController@stores');
  Route::get('product/{product}/images', 'ProductController@images');
  Route::resource('products', 'ProductController');

  Route::resource('images', 'ImageController');
  
  Route::resource('filters', 'FilterController');

  Route::resource('customers', 'CustomerController', ['only' => ['index', 'update', 'destroy']]);

  Route::get('/orders/{order}/products', 'OrderController@products');
  Route::post('/orders/{order}/products/{products}', 'OrderController@changeProduct');
  Route::delete('/orders/{order}/products/{product}', 'OrderController@removeProducts');
  Route::post('/orders/savestore', 'OrderController@saveStore');
  Route::get('/orders/{order}/store-orders', 'OrderController@storeOrders');
  Route::get('/orders/{order}/order-items', 'OrderController@orderItems');
  Route::patch('/order/{order}', 'OrderController@updateOrderStatus');
  Route::get('/orders/{order}/resend-message', 'OrderController@resendMessage');
  Route::patch('/orders/{order}/cancel-order', 'OrderController@cancelOrder');
  Route::get('/orders/sale', 'OrderController@storeSale');
  Route::post('/orders/status', 'OrderController@updateStatus');
  Route::resource('orders', 'OrderController');

  Route::post('/stores/{store}/products/{product}', 'StoreController@changeProduct');

  Route::resource('stores', 'StoreController');

  Route::resource('customers.addresses', 'AddressController');

  Route::post('/advertisements/{advertisement}/reactivate', 'AdvertisementController@reactivate');
  Route::post('/advertisements/{advertisement}/deactivate', 'AdvertisementController@deactivate');
  Route::resource('advertisements', 'AdvertisementController');

  Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'settings.index']);
  Route::get('/profile', 'AdminController@profile');
  Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'users.index']);
  Route::get('/users/create', ['uses' => 'AdminController@createUser', 'as' => 'users.create']);
  Route::patch('/users/{user}/change-password', ['uses' => 'AdminController@changePassword', 'as' => 'users.change-password']);
  Route::post('/users/', ['uses' => 'AdminController@storeUser', 'as' => 'users.store']);
  Route::delete('/users/{user}', ['uses' => 'AdminController@deleteUser', 'as' => 'users.destroy']);
  Route::get('/users/{user}', 'AdminController@deleteUser');
  Route::resource('/banners', 'BannerController');
  Route::resource('/offers', 'OfferController');

  Route::post('/update-token', 'AdminController@updateToken'); // fcm token update

  Route::post('/settings/delivery', 'AdminController@updateDeliverySettings');
  Route::patch('/settings/service', 'AdminController@updateSettings');
  Route::get('/pincodes', 'AdminController@pincodes');
  Route::get('/pincode-validate', 'AdminController@pincodeValidate');

  Route::post('/services/{service}/update-status', 'ServiceController@updateStatus');
  Route::post('/services/{service}/update-availability', 'ServiceController@updateAvailability');
  Route::resource('services', 'ServiceController');
});

Route::get('offerdelete', function() {
  Artisan::call('clear:offer');
  echo '<br>offer deleted';
});

app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    
	protected $guarded = ['id'];

	public function variant() {
        return $this->belongsTo('App\ProductVariant');
    }

    public function store() {
        return $this->belongsTo('App\Store');
    }

}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Offer;
use App\Store;
use App\ProductVariant;
use App\Product;

class OfferController extends Controller
{
    public function index(Request $request) {
    	if($request->ajax()) {
            $products = Product::where('active', true);
    		$offers = Offer::with('variant.product')->with('store');
            if($request->product) {
                $p = $request->product;
                $offers->whereHas('variant', function($query) use($p){
                    $query->whereIn('product_id', $p);
                });
            }
            if($request->startDate) {
                $s = $request->startDate;
                $e = $request->endDate;
                $offers->whereDate('from_date', '>=', $s)->whereDate('to_date', '<=', $e);
            }
    		return ['offers' => $offers->get(), 'length' => Offer::count(), 'products' => $products->get()];
    	}
    	return view('admin.offers.index');
    }

    public function create() {
    	$stores = Store::all();
    	return view('admin.offers.form', compact('stores'));
    }

    public function store(Request $request) {
    	$data = $request->only('variant_id', 'text', 'qty', 'store_id', 'from_date', 'to_date', 'offer_by');
    	$data['price'] = $request->price ? $request->price : null;
        $data['percent'] = $request->percent ? $request->percent : null;
    	$data['add_qty'] = $request->add_qty ? $request->add_qty : null;
    	$offer = Offer::firstOrCreate($data);

    	return ['status' => 'ok'];
		return redirect()->route('offers.index')->withSuccess('Offer created');
    }

    public function edit($id, Request $request) {
        $offer = Offer::with('variant.product')->with('store')->where('id', $id)->first();
        $prodId = $offer->variant->product_id;
        $variant = ProductVariant::where('product_id', $prodId)->get();
        $stores = Store::all();
        return view('admin.offers.form', compact('offer', 'stores', 'variant'));
    }

    public function update($id, Request $request) {
        $offers = Offer::find($id);
        $data = $request->only('variant_id', 'text', 'qty', 'store_id', 'from_date', 'to_date', 'offer_by');
        $data['price'] = $request->price ? $request->price : null;
        $data['percent'] = $request->percent ? $request->percent : null;
        $data['add_qty'] = $request->add_qty ? $request->add_qty : null;
        $offers->update($data);
        return "success";
    }

    public function destroy(Offer $offer) {
        $offer->delete();
        return redirect()->route('offers.index')->withSuccess('Offer deleted');
    }
}

resources/views/admin/offers/form.blade.php
@extends('layouts.admin-master')

@section('title', isset($offer) ? 'Edit Offer - ' : 'Create Offer')

@section('scripts')
	<template id="offerform">
		<div>
			<div class="title">
				<h3>{{ isset($offer) ? 'Edit Offer' : 'Create Offer' }}</h3>
			</div>
			<div class="col-md-9">
				<form class="form-horizontal" action="{{ route('offers.store') }}" method="POST" id="order-form" data-parsley-validate>
					{{ csrf_field() }}
					<div class="form-group">
			        	<label class="control-label col-md-4">Product</label>
			        	<div class="col-md-8">
			        		<input type="text" class="form-control" id="product_name" v-model="product.name" required>
							<div v-if="invalidProduct">
								<ul class="parsley-errors-list filled">
									<li class="parsley-required">Invalid product</li>
								</ul>
							</div>
			        	</div>
			        </div>
			        <div id="variantDiv" class="form-group">
			        	<label class="control-label col-md-4">Type
			        	</label>
			        	<div class="col-md-8">
			        		<select class="form-control" v-model="product.variant" id="variantSelect">
			        			<option v-bind:value="variant.id" v-for="variant in product.variants">@{{ variant.type + ' - ' + variant.price }}</option>
			        		</select>
			        	</div>
			        </div>
			        <div class="form-group">
			        	<label class="control-label col-md-4">Offer Text</label>
			        	<div class="col-md-8">
			        		<input type="text" class="form-control" v-model="offer_text" required>
			        	</div>
			        </div>
			        <div class="form-group">
			        	<label class="control-label col-md-4">Offer Qty</label>
			        	<div class="col-md-8">
			        		<input type="text" class="form-control" v-model="offer_qty" required>
			        	</div>
			        </div>
			        <div class="form-group">
			        	<label class="control-label col-md-4">Offer By</label>
			        	<div class="col-md-8">
			        		<select class="form-control" id="offerBy" v-model="offerBy">
			        			<option value="q">Quantity</option>
			        			<option value="dp">Discount percentage</option>
			        			<option value="dpr">Discount price</option>
			        		</select>
			        	</div>
			        </div>
			        <div class="form-group" id="addQty">
			        	<label class="control-label col-md-4">Additional Qty</label>
			        	<div class="col-md-8">
			        		<input type="text" class="form-control" v-model="add_qty">
			        	</div>
			        </div>
			        <div class="form-group" id="prDiv" hidden>
			        	<label class="control-label col-md-4"></label>
			        	<div class="col-md-4">
			        		<input type="text" class="form-control" v-model="percent">
			        	</div>
			        	<div class="col-md-4">
			        		<input type="text" class="form-control" placeholder="Amount after Offer" v-model="amount">
			        	</div>
			        </div>
			        <div class="form-group">
			        	<label class="control-label col-md-4">Starting Date</label>
			        	<div class="col-md-8">
			        		<input type="text" class="form-control" v-model="from_date" name="start_date" placeholder="dd/mm/yyyy" />
			        	</div>
			        </div>
			        <div class="form-group">
			        	<label class="control-label col-md-4">Expiry Date</label>
			        	<div class="col-md-8">
			        		<input type="text" class="form-control" v-model="to_date" name="end_date" placeholder="dd/mm/yyyy" />
			        	</div>
			        </div>
			        <div id="storeDiv" class="form-group">
			        	<label class="control-label col-md-4">Store
			        	</label>
			        	<div class="col-md-8">
			        		<select class="form-control" id="store_id" name="store_id" v-model="store">
			        		<option value>Select a store</option>
								<option v-for="store in order_stores" v-bind:value="store.id">
					                @{{ store.name }}
					            </option>

					        </select>
			        	</div>
			        </div>
			        <div class="form-group">
						<div class="col-md-8 col-md-offset-4">
							<button type="submit" class="btn btn-success" v-on:click="submit($event)">Save</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</template>	
	<script>
		var stub_product = {
			name: '{!! $offer->variant->product->name or '' !!}',
			qty: '{!! $offer->variant->qty or 0 !!}',
			price: '{!! $offer->variant->price or 0 !!}',
			variants: {!! json_encode( isset($offer) ? $variant : []) !!},
			variant: '{!! $offer->variant->id or 0 !!}',
		};
		var engine;

	  	var child = new Vue({
	    	el: '#v-container',
	    	data: function() {
				return {
					mode: '{!! isset($offer) ? 'edit' : 'new' !!}',
					product: stub_product,
					invalidProduct: false,
					offer_text: '{!! $offer->text or '' !!}',
					offer_qty: '{!! $offer->qty or '' !!}',
					add_qty: '{!! $offer->add_qty or '' !!}',
					offerBy: '{!! $offer->offer_by or '' !!}',
					percent: '{!! $offer->percent or '' !!}',
					order_stores: {!! json_encode($stores) !!},
					store: '{!! $offer->store->id or '' !!}',
					from_date: '{!! $offer->from_date or '' !!}',
					to_date: '{!! $offer->to_date or '' !!}',
					amount: '{!! $offer->price or '' !!}'
				}
			},
			watch: {
				percent: function(val) {
					var self = this;
					if(self.product.variant != "") {
						self.variant = self.product.variants.filter(function(p) {
							return p.id == self.product.variant;
						})[0];
					}

					if(self.offerBy == 'dpr') {
						self.amount =  self.variant.price - self.percent;
					} else if (self.offerBy == 'dp') {
						self.amount = self.variant.price - (self.variant.price * self.percent / 100);
					}
				}
			},
			methods: {
				submit: function(e) {
					e.preventDefault();
					var form = $("#order-form").parsley();
					form.validate();

					if(form.isValid()) {
						var self = this;
						var curr_store = this.store;
						var prod_store = this.order_stores.filter(function(s) {
							return s.id == curr_store;
						})[0];
						data = {
							variant_id: this.product.variant,
							text: this.offer_text,
							qty: this.offer_qty,
							offer_by: this.offerBy,
							add_qty: this.offerBy == 'q' ? this.add_qty : '',
							percent: this.offerBy != 'q' ? this.percent : '',
							price: this.amount != undefined ? this.amount : '',
							from_date: this.from_date,
							to_date: this.to_date,
							store_id: prod_store.id,
							_token: '{{ csrf_token() }}'
						}
						if(self.mode == 'edit') data._method = 'PATCH';
						$.ajax({
							url: '/admin/offers/{{ $offer->id or '' }}',
							method: 'POST',
							data: data,
							success: function(rsp) {
								console.log(rsp);
								window.location.href = '/admin/offers';
							}
						})
					} 
				}
			},
	    	mounted: function() {
	    		if($('#offerBy').val() == 'dp') {
					$('#addQty').hide();
					$('#prDiv label').text("Percentage");
					$('#prDiv').show();
				} else if($('#offerBy').val() == 'dpr') {
					$('#addQty').hide();
					$('#prDiv label').text("Amount");
					$('#prDiv').show();
				} else {
					$('#prDiv').hide();
					$('#addQty').show();
				}
    			var self = this;
				engine = new Bloodhound({
					datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
					queryTokenizer: Bloodhound.tokenizers.whitespace,
					remote: {
						url: '/admin/products?q=%QUERY&thumb=true',
						wildcard: '%QUERY',
						transform: function(rsp) {
							return rsp.data;
						}
					}
				})
    			$("#product_name").typeahead({
					highlight: true
				},
				{
					name: 'product-name',
					display: 'name',
					source: engine
				})
				.bind('typeahead:select', function(ev, suggestion) {
					self.product.price = suggestion.price;
					self.product.id = suggestion.id;
					self.product.name = suggestion.name;
					self.product.image = suggestion.image;
					self.product.packet = suggestion.packet;
					self.product.type = suggestion.type;
					self.product.variants = suggestion.variants;
					self.product.variant = suggestion.variants[0].id;
					// self.$forceUpdate();
				});
				$('#offerBy').change(function() {
					if($('#offerBy').val() == 'dp') {
						$('#addQty').hide();
						$('#prDiv label').text("Percentage");
						$('#prDiv').show();
					} else if($('#offerBy').val() == 'dpr') {
						$('#addQty').hide();
						$('#prDiv label').text("Amount");
						$('#prDiv').show();
					} else {
						$('#prDiv').hide();
						$('#addQty').show();
					}
				});
				var date_format = 'DD/MM/YYYY';
				$('input[name="start_date"]').daterangepicker({
	        		singleDatePicker: true,
		            format: date_format
	        	}).on('apply.daterangepicker', function(ev, picker) {
				    self.from_date = picker.startDate.format('YYYY-MM-DD');
				});
	    		$('input[name="end_date"]').daterangepicker({
	        		singleDatePicker: true,
		            format: date_format,
		            drops: 'up'
	        	}).on('apply.daterangepicker', function(ev, picker) {
				    self.to_date = picker.endDate.format('YYYY-MM-DD');
				});;
    		},
	    	template: '#offerform'
	  	});

	</script>	
@endsection

resources/views/admin/offers/index.blade.php
@extends('layouts.admin-master')

@section('title', 'Offers')

@section('head')
<style>
.calendar, .ranges {
	float: left;
}
.table thead tr th {
	white-space: nowrap;
}
.table-responsive .table {
  box-shadow: none;
  margin-bottom: 0;
}
.table-responsive {
  box-shadow: 0 0 3px 1px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
}
</style>
@endsection

@section('scripts')
	<template id="offerview">
	  	<div>
	    	<div class="toolbar">
	      		<div class="leading">
	      			<h3> Offers </h3>
	      		</div>
	      		<div class="buttons">
		        	<a class="btn btn-success" href="{{ route('offers.create') }}"><i class="fa fa-plus"></i> Add new</a>
		        	<a class="btn btn-default" data-toggle="modal" data-target="#productModal"><i class="fa fa-filter"></i> Product Filter <span class="prodlbl"></span></a>
		      	</div>
	      	</div>
	      	<div class="toolbar">
	      		<div class="leading">
	      		</div>
	      		<div class="form-control search-input">
			        <i class="fa fa-calendar"></i>
			        <input id="date" name="date_filter" type="text" placeholder="Enter date to search">
			        <button class="clear" v-on:click="clearDate()">
			          <i class="fa fa-times-circle"></i>
			        </button>
			    </div>
	      	</div>

      		<div class="table-responsive" style="">
	      	<div class="table-container">
		      	<table id="offer-table" class="table">
		        	<thead>
			          	<tr>
			            	<th>Product</th>
			            	<th>Type</th>
			            	<th>Offer Qty</th>
			            	<th>Offer Price</th>
			            	<th>Additional Qty</th>
			            	<th>Offer Text</th>
			            	<th>Valid from</th>
			            	<th>Valid to</th>
			            	<th>Store</th>
			            	<th>Actions</th>
			          	</tr>
		        	</thead>
		        	<tbody ref="table_body">
		          		<tr v-for="offer in offers">
		          			@verbatim
		          				<td>{{ offer.variant.product.name }}</td>
			            		<td>{{ offer.variant.type }}</td>
			            		<td>{{ offer.qty }}</td>
			            		<td>{{ offer.price }}</td>
			            		<td>{{ offer.add_qty }}</td>
			            		<td>{{ offer.text }}</td>
			            		<td>{{ offer.from_date }}</td>
			            		<td>{{ offer.to_date }}</td>
			            		<td v-if="offer.store != null">{{ offer.store.name }} </td><td v-else></td>
			            		<td>
			              			<a v-bind:href="'/admin/offers/' + offer.id + '/edit'" class="btn btn-xs btn-primary">Edit</a>&nbsp;<button type="button" class="btn btn-xs btn-danger" v-on:click="deleteOffer(offer)">Delete</button>
			            		</td>
		            		@endverbatim
		          		</tr>
		          		<tr v-if="!offers.length">
		          			<td colspan="10" align="center">No offers</td>
		          		</tr>
		        	</tbody>
		      	</table>
		    </div>
	      	</div>
		    <div id="productModal" class="modal fade" role="dialog">
			  <div class="modal-dialog">

			    <!-- Modal content-->
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal">&times;</button>
			        <h4 class="modal-title">Select products to filter</h4>
			      </div>
			      <div class="modal-body">
			      	<label class="control-label">Products </label>
			        <select multiple id="productSelect" style="width:400px">
				        	<option v-bind:value="product.id" v-for="product in products">@{{ product.name }}</option>
		    		</select>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			        <button type="button" class="btn btn-success" v-on:click="reloadOffers()">OK</button>
			      </div>
			    </div>

			  </div>
			</div>
	    </div>
	</template>

<script>
	var OfferView = Vue.extend({
		data: function() {
			return {
				offers: [],
				products: []
			}
		},
		methods: {
			clearDate: function() {
				$('#date').val('');
				this.start = '';
				this.stop = '';
				this.reloadOrders();
			},
			deleteOffer: function(offer) {
				var self = this;
				if(confirm('Are you sure you want to delete this offer? This cannot be undone!')) {
					$.post('/admin/offers/' + offer.id, {
						_method: 'DELETE',
						_token: '{{ csrf_token() }}'
					}).success(function(data) {
						self.offers = self.offers.filter(function(o) {
							return o.id != offer.id;
						});
					}).error(function(err) {
						console.log(err.responseText);
					});
				}
			},
			reloadOffers: function() {
				var self = this;
				var productId = $( "#productSelect" ).val();
				var data = {
					product: productId,
					startDate: this.start,
					endDate: this.stop
				}
				$.ajax({
					url: '/admin/offers?' + $.param(data),
					method: 'GET',
					cache: false,
					success: function(response) {
						self.offers = response.offers;
						self.products = response.products;
					}
				});
				$('#productModal').modal('hide');
				$('.prodlbl').html($('#productModal option:selected').length);
			}
		},
		mounted: function() {
			vm.$on('reloadOffers', this.reloadOffers);
			this.reloadOffers();

			var self = this;
			$('#date').daterangepicker({
		      calender_style: "picker_1",
		  	  format: 'YYYY-MM-DD',
		  	  opens: 'left',
		    }, function(start, end, label) {
		      console.log(start.toISOString(), end.toISOString(), label);
		    }).on('apply.daterangepicker', function(ev, picker) {
		        self.start = picker.startDate.format('YYYY-MM-DD');
		        self.stop = picker.endDate.format('YYYY-MM-DD');
		        self.reloadOffers();
		    });

			$("#productSelect").select2({
		    	placeholder: "Select product",
		    	allowClear: true
		    });
		},
		template: '#offerview',
	});
  var child = new Vue({
	parent: vm,
	el: '#v-container',
	render: function(createElement) {
		return createElement(OfferView);
	}
});

</script>
@endsection