routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['domain' => 'spa.telybazaar.app'], function() {
  Route::get('/', function() {
    return view('admin.spa');
  });
});

Route::get('/', function () {
  // return view('welcome');
  return view('coming-soon');
});

// Route::get('/test', 'API\ProductController@test');
Route::get('test', function() {

    return \App\Category::find(1)->descendantsAndSelf()->pluck('id')->all();
  // return array_unique(\App\Store::all()->pluck('pin')->all());
  // return \App\OrderItem::first()->product;
});
Route::get('/store-based', 'API\ProductController@storeBased');
Route::get('/product-based', 'API\ProductController@productBased');
Route::get('/product-based-single-store', 'API\ProductController@productBasedSingleStore');
Route::get('/calculate-distance', 'API\OrderController@calculateDistance');
Route::get('/reindex-category-names', function() {
  $categories = App\Category::all();
  function findFullName($category) {
    static $names = [];
    array_unshift($names, $category->name);
    if($category->parent_id) {
      return findFullName($category->parent);
    } else {
      $data = implode(' > ', $names);
      $names = [];
      return $data;
    }
  }
  foreach($categories as $category) {
    $category->fullname = findFullName($category);
    echo $category->fullname . '<br>';
    $category->save();
  }
});

Route::get('/login', 'Auth\LoginController@showLoginForm');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/customers', function() {
  return response()->json(\App\Customer::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/address', function() {
  return response()->json(\App\Address::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/products', function() {
  return response()->json(\App\Product::with('stores')->get(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/orders', function() {
  return response()->json(\App\Order::with('storeOrders.orderItems')->get(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/stores', function() {
  return response()->json(\App\Store::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/sample-product-seed', function() {
  foreach(range(0, Request::get('count', 10) - 1) as $i) {
    DB::table('products')->insert([
      'name' => 'foozie',
      'qty' => 20,
      'price' => 20,
      'purchase_price' => 20,
      'category_id' => 1
    ]);
  }
  echo 'seeded ' . (Request::get('count', 10)) . ' items';
});

Route::get('delete-all-products', function() {
  DB::table('products')->delete();
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
  Route::get('/dashboard', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
  Route::get('/dashboard/installs-data', 'DashboardController@installsData');
  Route::get('/dashboard/sales-data', 'DashboardController@salesData');
  Route::get('/notifications', 'AdminController@notifications');

  Route::get('category/tree', 'CategoryController@tree');
  Route::resource('categories', 'CategoryController');

  Route::get('product/{product}/stores', 'ProductController@stores');
  Route::get('product/{product}/images', 'ProductController@images');
  Route::resource('products', 'ProductController');

  Route::resource('images', 'ImageController');
  
  Route::resource('filters', 'FilterController');

  Route::resource('customers', 'CustomerController', ['only' => ['index', 'update', 'destroy']]);

  Route::get('/orders/{order}/products', 'OrderController@products');
  Route::post('/orders/{order}/products/{products}', 'OrderController@changeProduct');
  Route::delete('/orders/{order}/products/{product}', 'OrderController@removeProducts');
  Route::post('/orders/savestore', 'OrderController@saveStore');
  Route::get('/orders/{order}/store-orders', 'OrderController@storeOrders');
  Route::get('/orders/{order}/order-items', 'OrderController@orderItems');
  Route::patch('/order/{order}', 'OrderController@updateOrderStatus');
  Route::get('/orders/{order}/resend-message', 'OrderController@resendMessage');
  Route::patch('/orders/{order}/cancel-order', 'OrderController@cancelOrder');
  Route::get('/orders/sale', 'OrderController@storeSale');
  Route::post('/orders/status', 'OrderController@updateStatus');
  Route::resource('orders', 'OrderController');

  Route::post('/stores/{store}/products/{product}', 'StoreController@changeProduct');

  Route::resource('stores', 'StoreController');

  Route::resource('customers.addresses', 'AddressController');

  Route::post('/advertisements/{advertisement}/reactivate', 'AdvertisementController@reactivate');
  Route::post('/advertisements/{advertisement}/deactivate', 'AdvertisementController@deactivate');
  Route::resource('advertisements', 'AdvertisementController');

  Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'settings.index']);
  Route::get('/profile', 'AdminController@profile');
  Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'users.index']);
  Route::get('/users/create', ['uses' => 'AdminController@createUser', 'as' => 'users.create']);
  Route::patch('/users/{user}/change-password', ['uses' => 'AdminController@changePassword', 'as' => 'users.change-password']);
  Route::post('/users/', ['uses' => 'AdminController@storeUser', 'as' => 'users.store']);
  Route::delete('/users/{user}', ['uses' => 'AdminController@deleteUser', 'as' => 'users.destroy']);
  Route::get('/users/{user}', 'AdminController@deleteUser');
  Route::resource('/banners', 'BannerController');
  Route::resource('/offers', 'OfferController');

  Route::post('/update-token', 'AdminController@updateToken'); // fcm token update

  Route::post('/settings/delivery', 'AdminController@updateDeliverySettings');
  Route::patch('/settings/service', 'AdminController@updateSettings');
  Route::get('/pincodes', 'AdminController@pincodes');
  Route::get('/pincode-validate', 'AdminController@pincodeValidate');

  Route::post('/services/{service}/update-status', 'ServiceController@updateStatus');
  Route::post('/services/{service}/update-availability', 'ServiceController@updateAvailability');
  Route::resource('services', 'ServiceController');
});

Route::get('offerdelete', function() {
  Artisan::call('clear:offer');
  echo '<br>offer deleted';
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $guarded = ['id'];

    protected $casts = [
    	'active' => 'boolean'
    ];

    public function scopeActive($q) {
    	return $q->where('active', 1);
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Service;

class ServiceController extends Controller
{
    
	public function index(Request $request) {
		if($request->ajax()) {
			$services = Service::all();
			return ['services' => $services];
		} else {
			return view('admin.services.index');
		}
	}

	public function create() {
		return view('admin.services.form');
	}

	public function store(Request $request) {
		$data = $request->except('_token');
		$data['available'] = $data['total'];
		Service::create($data);
		return redirect()->route('services.index')->with('message', 'Service created');
	}

	public function edit(Service $service) {
		return view('admin.services.form', compact('service'));
	}

	public function update(Request $request, Service $service) {
		$service->update($request->except('_token', '_method'));
		return redirect()->route('services.index')->with('message', 'Service updated');
	}

	public function delete(Service $service) {
		$service->delete();
		return ['status' => 'ok'];
	}

	public function updateStatus(Request $request, Service $service) {
		$service->update(['active' => $request->active]);
	}

	public function updateAvailability(Request $request, Service $service) {
		if($request->has('available')) {
			$service->update(['available' => $request->available]);
		} else {
			if($request->increase) {
				$service->increment('available');
			} else {
				$service->decrement('available');
			}
		}
	}

}

resources/views/admin/services/form.blade.php
@extends('layouts.admin-master')

@section('content')
<div>
	<div class="row">
		<div class="col-md-12">
			<div class="title">
				<h3>{{ (isset($service) ? 'Edit' : 'Create') . ' Service' }}</h3>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			@if(isset($service))
			<form class="form-horizontal" method="POST" action="{{ route('services.update', $service->id) }}">
				<input type="hidden" name="_method" value="PATCH">	
			@else
			<form class="form-horizontal" method="POST" action="{{ route('services.store') }}">
			@endif
				{{ csrf_field() }}
				<div class="form-group">
					<label class="col-md-4 control-label">Name</label>
					<div class="col-md-8">
						<input type="text" class="form-control" name="name" value="{{ $service->name or old('name') }}">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Area</label>
					<div class="col-md-8">
						<input type="text" class="form-control" name="area" value="{{ $service->area or old('area') }}">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Total Units</label>
					<div class="col-md-8">
						<input type="number" class="form-control" name="total" value="{{ $service->total or old('total') }}">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Active</label>
					<div class="col-md-8 checkbox">
						<label>
							<input type="hidden" name="active" value="0">
							{!! Form::checkbox('active', 1, isset($service) ? $service->active : old('active')) !!}
						</label>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-8 col-md-offset-4">
						<button class="btn btn-success" type="submit">Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.admin-master')

@section('head')
<style>
.table .form-control {
	width: 50px;
	display: inline-block;
	height: 22px;
	padding-left: 2px;
	padding-right: 2px;
	margin-left: 2px;
	margin-right: 2px;
}
</style>
@endsection

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="toolbar">
			<div class="leading">
				<a href="#" class="head">Services</a>
			</div>
		  <div class="buttons">
		    <a class="btn btn-success" href="{{ route('services.create') }}"><i class="fa fa-plus"></i> Add new</a>
		  </div>
		</div>
		<table class="table" id="services-table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Area</th>
					<th>Available Units</th>
					<th>Active</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>
@endsection

@section('scripts')

<script>
	var storesTable = $('#services-table').DataTable({
	    ajax: {
	      url: '{{ route('services.index') }}',
	      dataSrc: 'services'
	    },
	    rowCallback: function(row, data, index) {
	    	$(row).data('id', data.id);
	    },
	    columns: [
	      {
	      	data: 'name',
	      },
	      {
	      	data: 'area'
	      },
	      {
	      	data: null,
	        render: function(data, type, full, meta) {
          		return [
          			'<button class="btn btn-xs btn-default"><i class="fa fa-chevron-left"></i></button>',
      				'<input class="form-control" type="number" value="' + data.available + '" data-max=' + data.total + '>',
          			'<button class="btn btn-xs btn-default"><i class="fa fa-chevron-right"></i></button>',
          			'of ' + data.total
          		].join('');
	        }
	      },
	      {
	      	data: 'active',
	        render: function(data, type, full, meta) {
	        	var label = data ? '<span class="text-success">Yes</span>' : '<span class="text-danger">No</span>'
          		return '<input type="checkbox" ' + (data ? 'checked' : null) + ' data-id="' + full.id +'"/>';
	        }
	      },
	      {
	      	data: null,
	        render: function(data, type, full, meta) {
	          var buttons = '<a href="/admin/services/' + data.id + '/edit" class="btn btn-xs btn-primary">Edit</a>&nbsp;' +
	            '<button type="button" class="btn btn-xs btn-danger del-btn" data-id="' + data.id + '">Delete</button>';
	          return buttons;
	        }
	      }
	    ]
	}).on('draw.dt', function() {
		function showOkey(el) {
			var okey = $('<span>&nbsp;<i class="fa fa-check text-success"></i></span>');
			setTimeout(function() {
				el.parent().append(okey);
				setTimeout(function() {
					okey.remove();
				}, 2000);
			}, 250);
		}
		function changeAvailability(increase) {
			return function() {
				$(this).unbind().click(function() {
					var btn = $(this);
					var progress = $('<span>&nbsp;<i class="fa fa-refresh fa-spin"></i></span>');
					var input = btn[increase ? 'prev' : 'next']();
					var nextVal = parseInt(input.val()) + (increase ? +1 : -1);
					var within_bounds = input.data('max') >= nextVal && nextVal >= 0;
					if(within_bounds) {
						btn.parent().append(progress)
						$.ajax({
							url: '/admin/services/' + btn.closest('tr').data('id') + '/update-availability',
							data: {
								increase: +increase,
								_token: '{{ csrf_token() }}'
							},
							method: 'POST',
							success: function() {
								input.val(nextVal);
								progress.remove();
								showOkey(btn)
							}
						});
					}
				})
			};
		}
		$(this).find('button:has(.fa-chevron-right)').each(changeAvailability(true));
		$(this).find('button:has(.fa-chevron-left)').each(changeAvailability(false));
		$(this).find('input[type=number]').each(function() {
			$(this).unbind().on('input', _.debounce(function() {
				var progress = $('<span>&nbsp;<i class="fa fa-refresh fa-spin"></i></span>');
				var input = $(this);
				if(this.value != '') {
					var max = input.data('max');
					if(this.value > max || this.value < 0) {
						input.attr('title', 'Error')
							.data('content', 'This field should be between 0 to ' + max)
							.data('placement', 'top')
							.data('trigger', 'focus')
							.popover('show');
						return;
					} else {	
						input.popover('destroy');
					}
					input.parent().append(progress)
					$.ajax({
						url: '/admin/services/' + input.closest('tr').data('id') + '/update-availability',
						data: {
							available: this.value,
							_token: '{{ csrf_token() }}'
						},
						method: 'POST',
						success: function() {
							progress.remove();
							showOkey(input);
						},
						error: function(rsp) {
							if(rsp.status == 422) {
								progress.remove();
							}
						}
					});
				}
			}, 500));
		})
		$(this).find('input[type=checkbox]:visible').each(function() {
			new Switchery(this, {size: 'small'});
			var progress = $('<span>&nbsp;<i class="fa fa-refresh fa-spin"></i></span>');
			this.onchange = function() {
				var sw = $(this);
				sw.parent().append(progress)
				$.ajax({
					url: '/admin/services/' + sw.closest('tr').data('id') + '/update-status',
					data: {
						active: +this.checked,
						_token: '{{ csrf_token() }}'
					},
					method: 'POST',
					success: function() {
						progress.remove();
						showOkey(sw);
					}
				})
			};
		});
	});
	$(document).on('click', '.del-btn', function() {
		var self = $(this);
		var id = self.attr('data-id');
		if(confirm('Are you sure you want to delete this service? This cannot be undone!')) {
			$.post('/admin/service/' + id, {
				_method: 'DELETE',
				_token: '{{ csrf_token() }}'
			}).success(function(data) {
				console.log(data);
				storesTable.row(self.closest('tr')).remove().draw();
			}).error(function(err) {
				console.log(err.responseText);
			});
		}
	});
</script>

@endsection