routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['domain' => 'spa.telybazaar.app'], function() {
  Route::get('/', function() {
    return view('admin.spa');
  });
});

Route::get('/', function () {
  // return view('welcome');
  return view('coming-soon');
});

// Route::get('/test', 'API\ProductController@test');
Route::get('test', function() {

    return \App\Category::find(1)->descendantsAndSelf()->pluck('id')->all();
  // return array_unique(\App\Store::all()->pluck('pin')->all());
  // return \App\OrderItem::first()->product;
});
Route::get('/store-based', 'API\ProductController@storeBased');
Route::get('/product-based', 'API\ProductController@productBased');
Route::get('/product-based-single-store', 'API\ProductController@productBasedSingleStore');
Route::get('/calculate-distance', 'API\OrderController@calculateDistance');
Route::get('/reindex-category-names', function() {
  $categories = App\Category::all();
  function findFullName($category) {
    static $names = [];
    array_unshift($names, $category->name);
    if($category->parent_id) {
      return findFullName($category->parent);
    } else {
      $data = implode(' > ', $names);
      $names = [];
      return $data;
    }
  }
  foreach($categories as $category) {
    $category->fullname = findFullName($category);
    echo $category->fullname . '<br>';
    $category->save();
  }
});

Route::get('/login', 'Auth\LoginController@showLoginForm');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/customers', function() {
  return response()->json(\App\Customer::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/address', function() {
  return response()->json(\App\Address::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/products', function() {
  return response()->json(\App\Product::with('stores')->get(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/orders', function() {
  return response()->json(\App\Order::with('storeOrders.orderItems')->get(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/stores', function() {
  return response()->json(\App\Store::all(), 200, [], JSON_PRETTY_PRINT);
});

Route::get('/sample-product-seed', function() {
  foreach(range(0, Request::get('count', 10) - 1) as $i) {
    DB::table('products')->insert([
      'name' => 'foozie',
      'qty' => 20,
      'price' => 20,
      'purchase_price' => 20,
      'category_id' => 1
    ]);
  }
  echo 'seeded ' . (Request::get('count', 10)) . ' items';
});

Route::get('delete-all-products', function() {
  DB::table('products')->delete();
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
  Route::get('/dashboard', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
  Route::get('/dashboard/installs-data', 'DashboardController@installsData');
  Route::get('/dashboard/sales-data', 'DashboardController@salesData');
  Route::get('/notifications', 'AdminController@notifications');

  Route::get('category/tree', 'CategoryController@tree');
  Route::resource('categories', 'CategoryController');

  Route::get('product/{product}/stores', 'ProductController@stores');
  Route::get('product/{product}/images', 'ProductController@images');
  Route::resource('products', 'ProductController');

  Route::resource('images', 'ImageController');
  
  Route::resource('filters', 'FilterController');

  Route::resource('customers', 'CustomerController', ['only' => ['index', 'update', 'destroy']]);

  Route::get('/orders/{order}/products', 'OrderController@products');
  Route::post('/orders/{order}/products/{products}', 'OrderController@changeProduct');
  Route::delete('/orders/{order}/products/{product}', 'OrderController@removeProducts');
  Route::post('/orders/savestore', 'OrderController@saveStore');
  Route::get('/orders/{order}/store-orders', 'OrderController@storeOrders');
  Route::get('/orders/{order}/order-items', 'OrderController@orderItems');
  Route::patch('/order/{order}', 'OrderController@updateOrderStatus');
  Route::get('/orders/{order}/resend-message', 'OrderController@resendMessage');
  Route::patch('/orders/{order}/cancel-order', 'OrderController@cancelOrder');
  Route::get('/orders/sale', 'OrderController@storeSale');
  Route::post('/orders/status', 'OrderController@updateStatus');
  Route::resource('orders', 'OrderController');

  Route::post('/stores/{store}/products/{product}', 'StoreController@changeProduct');

  Route::resource('stores', 'StoreController');

  Route::resource('customers.addresses', 'AddressController');

  Route::post('/advertisements/{advertisement}/reactivate', 'AdvertisementController@reactivate');
  Route::post('/advertisements/{advertisement}/deactivate', 'AdvertisementController@deactivate');
  Route::resource('advertisements', 'AdvertisementController');

  Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'settings.index']);
  Route::get('/profile', 'AdminController@profile');
  Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'users.index']);
  Route::get('/users/create', ['uses' => 'AdminController@createUser', 'as' => 'users.create']);
  Route::patch('/users/{user}/change-password', ['uses' => 'AdminController@changePassword', 'as' => 'users.change-password']);
  Route::post('/users/', ['uses' => 'AdminController@storeUser', 'as' => 'users.store']);
  Route::delete('/users/{user}', ['uses' => 'AdminController@deleteUser', 'as' => 'users.destroy']);
  Route::get('/users/{user}', 'AdminController@deleteUser');
  Route::resource('/banners', 'BannerController');
  Route::resource('/offers', 'OfferController');

  Route::post('/update-token', 'AdminController@updateToken'); // fcm token update

  Route::post('/settings/delivery', 'AdminController@updateDeliverySettings');
  Route::patch('/settings/service', 'AdminController@updateSettings');
  Route::get('/pincodes', 'AdminController@pincodes');
  Route::get('/pincode-validate', 'AdminController@pincodeValidate');

  Route::post('/services/{service}/update-status', 'ServiceController@updateStatus');
  Route::post('/services/{service}/update-availability', 'ServiceController@updateAvailability');
  Route::resource('services', 'ServiceController');
});

Route::get('offerdelete', function() {
  Artisan::call('clear:offer');
  echo '<br>offer deleted';
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    
	protected $guarded = ['id'];

	public function addresses() {
		return $this->hasMany('App\Address');
	}

	public function orders() {
		return $this->hasMany('App\Order');
	}

}

app/Http/Controllers/API/CustomerController.php
<?php namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Customer;
use StoreLocator;
use App\Services\Messenger;
use DB;
use Validator;
use DateTime;

class CustomerController extends Controller {
    
	public function register(Request $request) {
		$key = $this->generateKey();
		$data = ['key' => $key];
		$customer = Customer::create($data);
		return response()->json(['status' => 'ok', 'key' => $key]);
	}

	private function generateKey() {
		return md5(microtime() . rand());
	}

	public function verifyMobile(Request $request) {
		$validator = Validator::make($request->all(), [
			'mobile' => 'required|digits:10'
		]);
		if($validator->fails()) {
			return [
				'status' => 'error',
				'msg' => $validator->errors()
			];
		}
		$mobile = $request->mobile;
		// $exists = DB::table('customers')
		// 	->where('mobile', $mobile)
		// 	->exists();
		// if($exists) {
		// 	return [
		// 		'status' => 'error',
		// 		'msg' => 'This number is already registered with Tely Bazaar'
		// 	];
		// }
		$otp = $this->generateOtp();
		$data = compact('otp', 'mobile');
		$data['created_at'] = new DateTime;
		$data['updated_at'] = new DateTime;
		$msg = 'Your OTP for Tely Bazaar is ' . $otp;
		DB::table('otp')
			->where('mobile', $mobile)
			->update([
				'active' => 0,
				'updated_at' => new DateTime
			]);
		DB::table('otp')->insert($data);
		$messenger = new Messenger;
		$messenger->sendMessage($request->mobile, $msg);
		return ['status' => 'ok'];
	}

	public function verifyOtp(Request $request) {
		$validator = Validator::make($request->all(), [
			'mobile' => 'required|digits:10',
			'otp' => 'required|digits:4'
		]);
		if($validator->fails()) {
			return [
				'status' => 'error',
				'msg' => $validator->errors()
			];
		}
		$mobile = $request->mobile;
		$otp = $request->otp;
		$exists = DB::table('otp')
			->where('otp', $otp)
			->where('mobile', $mobile)
			->where('active', 1)
			->exists();
		if($exists) {
			$key = $this->generateKey();
			DB::table('otp')
				->where('mobile', $mobile)
				->update([
					'active' => 0,
					'updated_at' => new DateTime
				]);
			Customer::create(compact('key', 'mobile'));
			return ['status' => 'ok', 'key' => $key];
		}
		return ['status' => 'error', 'msg' => 'Invalid OTP'];
	}

	private function generateOtp() {
		return rand(1000, 9999);
	}

	// this is probably the first call during startup after registration
	public function updatePin(Request $request) {
		// $customer = Customer::whereKey($request->key)->first();
		$customer = Customer::firstOrCreate(['key' => $request->key]); // enable zombies
		$customer->update(['pin' => $request->pin]);
		$stores = StoreLocator::nearbyStores($request->pin)->count();
		return response()->json(['status' => 'ok', 'stores' => $stores]);
	}

}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Customer;
use App\User;
use App\Transformers\CustomerTransformer;

class CustomerController extends Controller {

	public function index(Request $request) {
		if($request->ajax()) {
			$query = Customer::query();
			$query->with('orders');
			if($request->has('q')) {
				$q = $request->q;
				if(strpos($q, '#') !== false) {
					$query->where('id', str_replace('#', '', $q));
				} else {
					$query->where('mobile', 'like', '%' . $q . '%');
					$query->orWhere('key', 'like', '%' . $q . '%');
				}
			}
			$count = $query->count();
			if($request->has('offset')) {
				$query->skip($request->offset);
			}
			$query->take($request->input('limit', 10));
			$customers = $query->orderBy('id', 'desc')->get();
			$customers = fractal($customers, new CustomerTransformer)->toArray();
			return ['total' => $count, 'customers' => $customers['data']];
		}
		return view('admin.customers.index');
	}

	public function update(Customer $customer, Request $request) {

	}

	public function destroy(Customer $customer) {
		$customer->delete();
		return ['status' => 'ok'];
	}

}

resources/views/admin/customers/partials/address.blade.php
<div class="form-group">
	<label class="col-md-4 control-label">First Name <span class="text-danger">*</span></label>
	<div class="col-md-8">
		<input type="text" name="firstname" class="form-control" required>
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">Last Name <span class="text-danger">*</span></label>
	<div class="col-md-8">
		<input type="text" name="lastname" class="form-control" required>
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">Address Line 1 <span class="text-danger">*</span></label>
	<div class="col-md-8">
		<textarea class="form-control" name="address1" rows="5" required></textarea>
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">Address Line 2</label>
	<div class="col-md-8">
		<textarea class="form-control" name="address2" rows="5"></textarea>
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">City</label>
	<div class="col-md-8">
		<input type="text" name="city" class="form-control">
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">Area</label>
	<div class="col-md-8">
		<input type="text" name="area" class="form-control">
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">PIN <span class="text-danger">*</span></label>
	<div class="col-md-8">
		<input type="text" name="pin" class="form-control" required>
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">Email <span class="text-danger">*</span></label>
	<div class="col-md-8">
		<input type="email" name="email" class="form-control" required>
	</div>
</div>
<div class="form-group">
	<label class="col-md-4 control-label">Phone no <span class="text-danger">*</span></label>
	<div class="col-md-8">
		<input type="text" name="phone" class="form-control" required>
	</div>
</div>

resources/views/admin/customers/partials/form.blade.php
@section('content')
@if(isset($customer))
<ul class="nav nav-tabs">
	<li class="active"><a href="#data" data-toggle="tab">Data</a></li>
	<li><a href="#address-book" data-toggle="tab">Address Book</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="data">
@endif
		<div class="col-md-8">
			@include('admin.partials.alerts')
			@if(isset($customer))
			<form method="POST" action="{{ route('customers.update', $customer) }}" class="form-horizontal">
				<input type="hidden" name="_method" value="PATCH">
			@else
			<form method="POST" action="{{ route('customers.store') }}" class="form-horizontal">
			@endif
				{{ csrf_field() }}
				<div class="form-group">
					<label class="col-md-4 control-label">Name</label>
					<div class="col-md-8">
						<input type="text" name="name" class="form-control" value="{{ $customer->user->name or old('name') }}">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Email</label>
					<div class="col-md-8">
						<input type="email" name="email" class="form-control" value="{{ $customer->user->email or old('email') }}">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Password</label>
					<div class="col-md-8">
						<input type="password" name="password" class="form-control">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Confirm Password</label>
					<div class="col-md-8">
						<input type="password" name="password_confirmation" class="form-control">
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Active</label>
					<div class="col-md-8 checkbox">
						<label>
							<input type="hidden" name="active" value="0">
							{!! Form::checkbox('active', 1, isset($customer) ? $customer->active : old('active')) !!}
						</label>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-8 col-md-offset-4">
						<button type="submit" class="btn btn-success">Save</button>
					</div>
				</div>
			</form>
		</div>
@if(isset($customer))
	</div>
	<div class="tab-pane" id="address-book">
		<div class="toolbar">
			<div class="pull-right">
				<button class="btn btn-success" data-toggle="modal" data-target="#address-modal">Add new</button>
			</div>
			<div class="clearfix"></div>
		</div>
		<table class="table table-bordered" id="address-table">
			<thead>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Address Line 1</th>
					<th>Phone</th>
					<th>Email</th>
					<th>PIN</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				@forelse($customer->addresses as $address)
				<tr>
					<td>{{ $address->firstname }}</td>
					<td>{{ $address->lastname }}</td>
					<td>{{ $address->address1 }}</td>
					<td>{{ $address->phone }}</td>
					<td>{{ $address->email }}</td>
					<td>{{ $address->pin }}</td>
					<td>
						<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#address-modal">Edit</button>
						<button type="button" class="btn btn-danger del-btn" data-id="{{ $address->id }}">Delete</button>
					</td>
				</tr>
				@empty
				<tr>
					<td colspan="7" align="center">No data</td>
				</tr>
				@endforelse
			</tbody>
		</table>
	</div>
</div>
@include('admin.partials.addressmodal')
@endif
@endsection

@if(isset($customer))
@section('scripts')
<script>
function deleteHandler(e) {
	var btn = $(this);
	var id = btn.attr('data-id');
	if(confirm('Are you sure you want to delete this address? This cannot be undone!')) {
		$.post('/admin/customers/{{ $customer->id }}/addresses/' + id, {
			_token: '{{ csrf_token() }}',
			_method: 'DELETE'
		})
		.success(function(data) {
			// console.log(data);
			btn.closest('tr').remove();
			var tbody = $("#address-table tbody");
			if(tbody.children().length == 0) {
				tbody.append('<tr><td colspan="7" align="center">No data</td></tr>');
			}
		})
		.error(function(err) {
			console.log(err.responseText);
		});
	}
}
$('.del-btn').click(deleteHandler);
$("#address-modal .btn-primary").click(function() {
	console.log('validating')
	var valid = $("#address-form").parsley().validate();
	if(valid) {
		var data = {};
		$.each($('#address-form').serializeArray(), function() {
			data[this.name] = this.value;
		});
		data._token = '{{ csrf_token() }}';
		// console.log(data);
		$.post('{{ route('customers.addresses.store', $customer) }}', data)
			.success(function(rsp) {
				// console.log(rsp)
				var rows = $("#address-table tbody tr");
				if(rows.length == 1 && rows.eq(0).find('td').length == 1) {
					rows.remove();
				}
				$("#address-table tbody").append(
					'<tr>' + 
						'<td>' + data.firstname + '</td>' +
						'<td>' + data.lastname + '</td>' +
						'<td>' + data.address1 + '</td>' +
						'<td>' + data.phone + '</td>' +
						'<td>' + data.email + '</td>' +
						'<td>' + data.pin + '</td>' +
						'<td>' +
							'<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#address-modal">Edit</button>&nbsp;' +
							'<button type="button" class="btn btn-danger del-btn" data-id="' + rsp.id + '">Delete</button>' +
						'</td>' +
					'</tr>'
				);
				$('#address-form').get(0).reset();
				$("#address-form").parsley().reset();
				$('.del-btn').unbind().click(deleteHandler);
				$("#address-modal").modal('hide');
			})
			.error(function(err) {
				console.log(err.responseText)
			});
	}
});
</script>
@endsection
@endif